"use client";

import { useState, useRef, useCallback } from "react";
import { DataTable } from "@/components/admin/data-table";
import { StatusDropdown } from "@/components/admin/status-dropdown";
import { SearchFilterBar } from "@/components/admin/search-filter-bar";
import {
  getProjectOutlines,
  updateProjectOutlineStatus,
} from "@/lib/actions/admin";

interface Props {
  initialData: Record<string, unknown>[];
  initialCount: number;
}

const STATUS_OPTIONS = ["draft", "reviewed", "approved", "finalized"];

export function OutlinesTable({ initialData, initialCount }: Props) {
  const [data, setData] = useState(initialData);
  const [count, setCount] = useState(initialCount);
  const [page, setPage] = useState(1);
  const filtersRef = useRef<{ search?: string; status?: string }>({});
  const debounceRef = useRef<ReturnType<typeof setTimeout>>(undefined);

  const fetchData = useCallback(async (p: number) => {
    const result = await getProjectOutlines(p, 20, filtersRef.current);
    setData(result.data);
    setCount(result.count);
    setPage(p);
  }, []);

  function handlePageChange(newPage: number) {
    fetchData(newPage);
  }

  function handleStatusFilter(status: string | null) {
    filtersRef.current = { ...filtersRef.current, status: status ?? undefined };
    fetchData(1);
  }

  const columns = [
    {
      key: "id",
      header: "ID",
      render: (row: Record<string, unknown>) =>
        (row.id as string).slice(0, 8) + "...",
    },
    { key: "version", header: "Version" },
    { key: "generated_by", header: "Generated By" },
    {
      key: "status",
      header: "Status",
      render: (row: Record<string, unknown>) => (
        <StatusDropdown
          id={row.id as string}
          currentStatus={row.status as string}
          options={STATUS_OPTIONS}
          onUpdate={updateProjectOutlineStatus}
        />
      ),
    },
    {
      key: "created_at",
      header: "Created",
      render: (row: Record<string, unknown>) =>
        new Date(row.created_at as string).toLocaleDateString(),
    },
  ];

  return (
    <div className="space-y-4">
      <SearchFilterBar
        statusOptions={STATUS_OPTIONS}
        onSearch={() => {}}
        onStatusFilter={handleStatusFilter}
      />
      <DataTable
        columns={columns}
        data={data}
        totalCount={count}
        page={page}
        perPage={20}
        onPageChange={handlePageChange}
      />
    </div>
  );
}
